pull_request_rules:
  - name: Testing auto merge from github-actions bot
    conditions:
      - author=github-actions[bot]
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
